name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Build with Eleventy
        run: npx @11ty/eleventy
      - name: Upload GitHub Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./_site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5